[workspace]
members = [
    "server", 
    "client",
]

resolver = "2"  # version of rustc to use (compiler)

[profile.dev]
opt-level = 0  # no optimization

[profile.release]
opt-level = 3  # fully optimized
